a=set()
b=set()
for i in range(1,11):
   a.add(i*i)
   b.add(i*i*i)
print("set 1:",a)
print("set 2:",b)
c={200,300}
print("New set 3:",c)
a.update(c)
print("The updated set 1 is:",a)
a.pop()
print("After poping,set 1:",a)
a.remove(200)
print("After removing 200, set 1:",a)
a.add(500)
print("After adding 500,set 1:",a)
b.clear()
prin("After clearing,set 2:",b)
